### ISSUE TITLE
`_find_transliteration` doesn't work for cdli_corpus (no metadata)

### ISSUE THREAD

**Issue by adeloucas** [adeloucas/GSoC-Akkadian#56]
`_find_transliteration` doesn't work for cdli_corpus (no metadata)

```
Traceback (most recent call last):
  File "C:/Users/andrew.deloucas/GSoC-Akkadian/Testpad.py", line 14, in <module>
    cc.ingest_text_file(fi.file_lines)
  File "C:\Users\andrew.deloucas\GSoC-Akkadian\Importer\cdli_corpus.py", line 155, in ingest_text_file
    self._ingest(text_lines)
  File "C:\Users\andrew.deloucas\GSoC-Akkadian\Importer\cdli_corpus.py", line 141, in _ingest
    metadata = self._find_metadata(file_lines)
  File "C:\Users\andrew.deloucas\GSoC-Akkadian\Importer\cdli_corpus.py", line 111, in _find_metadata
    if text[0].startswith('&'):
IndexError: list index out of range
```

Initial thoughts: is there a way to solve for this without the `try` function?

**Comment by adeloucas** [comment]
intial solve:

`if text[0].startswith('Primary publication'):`
to
`if str(text).startswith('Primary publication:'):`

**Comment by adeloucas** [comment]
This has been solved.
