### ISSUE TITLE
sign_tokenizer chokes with determinatives

### ISSUE THREAD

**Issue by adeloucas** [adeloucas/GSoC-Akkadian#62]
```
text = cc.call_text('&P254226')

tk = Tokenizer()
for line in text:
    word = tk.word_tokenizer(line)
    print(word)
    for words in word:
        sign = tk.sign_tokenizer(words)
        print(sign)

Traceback (most recent call last):
  File "C:/Users/adeloucas/PycharmProjects/GSoCAkkadian/Testpad.py", line 22, in <module>
    sign = tk.sign_tokenizer(words)
  File "C:\Users\adeloucas\PycharmProjects\GSoCAkkadian\ATFConverter\tokenizer.py", line 193, in sign_tokenizer
    if signs_output[-1][0][-1] == "}":
IndexError: string index out of range
```
Word tokenizer works great! Upon breaking words into signs, the tokenizer is able to work through the text, but outputs the above soft issue. In looking at the text, here is where it struggles to work:

line: `[('a-na', 'akkadian'), ('ia-as2-ma-ah-{d}iszkur', 'akkadian')]`
words: `[('a', 'akkadian'), ('na', 'akkadian')]`, 
`[('ia', 'akkadian'), ('as2', 'akkadian'), ('ma', 'akkadian'), ('ah', 'akkadian'),` **`('{d}iszkur', 'akkadian')]`**

line: `[('qi2-bi2-ma', 'akkadian')]`
word: [('qi2', 'akkadian'), ('bi2', 'akkadian'), ('ma', 'akkadian')]

line: `[('um-ma', 'akkadian'), ('{d}utu-szi-{d}iszkur', 'akkadian')]`
words: `[('um', 'akkadian'), ('ma', 'akkadian')]`
**`[('d}utu-szi-{d', 'determinative')`**`, ('iszkur', 'akkadian')]`

line: `[('a-bu-ka-a-ma', 'akkadian')]`
word: `[('a', 'akkadian'), ('bu', 'akkadian'), ('ka', 'akkadian'), ('a', 'akkadian'), ('ma', 'akkadian')]`

line: `[('asz-szum', 'akkadian'), ('_{lu2}nagar', 'sumerian'), ('mesz_', 'sumerian'), ('sza', 'akkadian'), ('tu-ut-tu-ul{ki}', 'akkadian')]`
words: `[('asz', 'akkadian'), ('szum', 'akkadian')]`
**`[('_{lu2}nagar', 'sumerian')]`**
`[('mesz', 'sumerian')]`
`[('sza', 'akkadian')]`
`[('tu', 'akkadian'), ('ut', 'akkadian'), ('tu', 'akkadian'), ('ul', 'akkadian'),` **`('ki', 'determinative')]`**

currently, this is what it looks like:

https://github.com/adeloucas/GSoC-Akkadian/blob/c56ab88360e722e662985d932061620da0705782/ATFConverter/tokenizer.py#L154-L200

**Comment by adeloucas** [comment]
first determinatives are fixed with non-greedy regex ({(.+?)}), but still am looking for solutions for embedded determinatives (_{lu2}nagar), as well as determinatives attached to the last sign (ul{ki} and {d}ishkur)

**Comment by adeloucas** [comment]
Post ["WIP sign_tokenizer debugging"](https://github.com/adeloucas/GSoC-Akkadian/commit/58fad978e52c19a796be30e5b47e7ce38beff2e5#diff-d0c752061d688a790ce79244b58d8092L166):

What I have works flawlessly EXCEPT THESE RARE (?) CASES: 
```
['{geš}ma2-tu{hi-a}', 'li-pu-šu']
[('gesz', 'determinative'), ('ma2', 'akkadian'), ('tu{hi', 'akkadian'), ('ma2-tu', 'akkadian'), ('hi-a', 'determinative')]
```
Goal for tomorrow: examine (and solve) why the redundancy. I can take an educated guess why...

**Comment by willismonroe** [comment]
Hey Andrew,

since we're running up against a rather hard deadline.  I have a radical
idea for a slight retooling.
Create a flag for the cdli_corpus class that switches it to target
normalized texts.  You can detect those by look for line that start with
'#tr.ts'

I just did a search and we've got a sizable corpus of material to work
with.  The normalized texts will give us a really potent dataset to work
from.

Let me know what you think...

**Comment by willismonroe** [comment]
Check out my commit, you can test it with:

```
from Importer.file_importer import FileImport
from Importer.cdli_corpus import CDLICorpus
f = FileImport('texts/cdli_corpus.txt')
c = CDLICorpus()
f.read_file()
c._chunk_text(f.file_lines, only_normalization=True)
```

**Comment by adeloucas** [comment]
I'm having difficulty with running the test; I'll figure out what's going wrong on my end tomorrow. Once this is up and running, shall we all reconvene for final debrief?

**Comment by willismonroe** [comment]
Happy to meet tomorrow briefly to go over the normalization stuff.

**Comment by willismonroe** [comment]
Had a go at hacking this into something that checked each and every character instead... seems to work pretty well:

```
def sign_tokenizer(word):
    word_signs = []
    sign = ''
    language = word[1]
    determinative = False
    for char in word[0]:
        if determinative == True:
            if char == '}':
                determinative = False
                if len(sign) > 0:
                    word_signs.append((sign, 'determinative'))
                sign = ''
                language = word[1]
                continue
            else:
                sign += char
                continue
        else:
            if language == 'akkadian':
                if char == '{':
                    if len(sign) > 0:
                        word_signs.append((sign, language))
                    sign = ''
                    determinative = True
                    continue
                elif char == '_':
                    if len(sign) > 0:
                        word_signs.append((sign, language))
                    sign = ''
                    language = 'sumerian'
                    continue
                elif char == '-':
                    if len(sign) > 0:
                        word_signs.append((sign, language))
                    sign = ''
                    language = word[1] # or default word[1]?
                    continue
                else:
                    sign += char
            elif language == 'sumerian':
                if char == '{':
                    if len(sign) > 0:
                        word_signs.append((sign, language))
                    sign = ''
                    determinative = True
                    continue
                elif char == '_':
                    if len(sign) > 0:
                        word_signs.append((sign, language))
                    sign = ''
                    language = word[1]
                    continue
                elif char == '-':
                    if len(sign) > 0:
                        word_signs.append((sign, language))
                    sign = ''
                    language = word[1] # or default word[1]?
                    continue
                else:
                    sign += char
    if len(sign) > 0:    
        word_signs.append((sign, language))
    
    return word_signs
```

I'm sure there are ways to make it more efficient line ways but it's very descriptive right now which is a plus.

**Comment by adeloucas** [comment]
Solid! For cases like "_e2_-ka", are we looking at the sign ka being an akkadian phonetic for e2? That's the only bug I've been able to catch from this rewrite.
